/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projeto.matriz;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Thamires
 */
public class ProjetoMatriz extends javax.swing.JFrame {

    /**
     * Creates new form ProjetoMatriz
     */
    
    String[][] tabela = new String[10][3];
    int i = 0, j = 0;
    
    public ProjetoMatriz() {
        initComponents();
        painelcadastro.setVisible(false);
        campobrigatorio1.setVisible(false);
        campobrigatorio2.setVisible(false);
        campobrigatorio3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        painelEntrada = new javax.swing.JPanel();
        lblentrada = new javax.swing.JLabel();
        btcadastro = new javax.swing.JButton();
        imagem = new javax.swing.JLabel();
        painelcadastro = new javax.swing.JPanel();
        lblnome = new javax.swing.JLabel();
        lblcidade = new javax.swing.JLabel();
        lblestado = new javax.swing.JLabel();
        txnome = new javax.swing.JTextField();
        txcidade = new javax.swing.JTextField();
        txestado = new javax.swing.JTextField();
        btsalvar = new javax.swing.JButton();
        btsair = new javax.swing.JButton();
        btimprimir = new javax.swing.JButton();
        campobrigatorio1 = new javax.swing.JLabel();
        campobrigatorio2 = new javax.swing.JLabel();
        campobrigatorio3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        imagemcadastro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelEntrada.setBackground(new java.awt.Color(153, 0, 255));
        painelEntrada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblentrada.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblentrada.setForeground(new java.awt.Color(102, 204, 255));
        lblentrada.setText("Bem Vindo!");
        painelEntrada.add(lblentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 250, 60));

        btcadastro.setBackground(new java.awt.Color(0, 204, 255));
        btcadastro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btcadastro.setText("Cadastrar");
        btcadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcadastroActionPerformed(evt);
            }
        });
        painelEntrada.add(btcadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/WhatsApp Image 2024-09-27 at 09.39.25.jpeg"))); // NOI18N
        painelEntrada.add(imagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 470));

        painelcadastro.setBackground(new java.awt.Color(204, 204, 255));
        painelcadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblnome.setBackground(new java.awt.Color(204, 204, 255));
        lblnome.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 12)); // NOI18N
        lblnome.setText("Nome:");
        painelcadastro.add(lblnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 49, -1));

        lblcidade.setBackground(new java.awt.Color(204, 204, 255));
        lblcidade.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 12)); // NOI18N
        lblcidade.setText("Cidade:");
        painelcadastro.add(lblcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 49, -1));

        lblestado.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 12)); // NOI18N
        lblestado.setText("Estado:");
        painelcadastro.add(lblestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 49, -1));

        txnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnomeActionPerformed(evt);
            }
        });
        painelcadastro.add(txnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 382, -1));

        txcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txcidadeActionPerformed(evt);
            }
        });
        painelcadastro.add(txcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 267, -1));
        painelcadastro.add(txestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 208, -1));

        btsalvar.setBackground(new java.awt.Color(204, 102, 255));
        btsalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btsalvar.setForeground(new java.awt.Color(255, 255, 255));
        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });
        painelcadastro.add(btsalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        btsair.setBackground(new java.awt.Color(204, 102, 255));
        btsair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btsair.setForeground(new java.awt.Color(255, 255, 255));
        btsair.setText("Sair");
        btsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsairActionPerformed(evt);
            }
        });
        painelcadastro.add(btsair, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 58, -1));

        btimprimir.setBackground(new java.awt.Color(204, 102, 255));
        btimprimir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btimprimir.setForeground(new java.awt.Color(255, 255, 255));
        btimprimir.setText("Imprimir");
        btimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btimprimirActionPerformed(evt);
            }
        });
        painelcadastro.add(btimprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        campobrigatorio1.setForeground(new java.awt.Color(204, 102, 255));
        campobrigatorio1.setText("Esse campo é obrigatório!");
        painelcadastro.add(campobrigatorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        campobrigatorio2.setBackground(new java.awt.Color(255, 255, 255));
        campobrigatorio2.setForeground(new java.awt.Color(204, 102, 255));
        campobrigatorio2.setText("Esse campo é obrigatório!");
        painelcadastro.add(campobrigatorio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        campobrigatorio3.setBackground(new java.awt.Color(255, 0, 102));
        campobrigatorio3.setForeground(new java.awt.Color(204, 102, 255));
        campobrigatorio3.setText("Esse campo é obrigatório!");
        painelcadastro.add(campobrigatorio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        painelcadastro.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, 60));

        imagemcadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/WhatsApp Image 2024-09-27 at 11.07.12.jpeg"))); // NOI18N
        painelcadastro.add(imagemcadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelcadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(painelcadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txcidadeActionPerformed

    private void btsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btsairActionPerformed

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
         
        //Ver se todos os campos foram preenchidos
        
        if ((txnome.getText().trim().isEmpty()) || (txcidade.getText().trim().isEmpty()) || (txestado.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(this, "Para realizar o cadastro, é necessário que TODOS os campos sejam preenchidos!");
            
            if (txnome.getText().trim().isEmpty()) {
                campobrigatorio1.setVisible(true);
                if (txnome.getText().trim().isEmpty()) { // Coloca o foco se o campo estiver vazio
                txnome.requestFocus();}
                }
            
            else {
            campobrigatorio1.setVisible(false); // Ocultar mensagem se o campo estiver preenchido
             }
            
            if (txcidade.getText().trim().isEmpty()) {
                campobrigatorio2.setVisible(true);
                if (txcidade.getText().trim().isEmpty()) { // Coloca o foco se o campo estiver vazio
                txcidade.requestFocus();
                }
                
            }else {
            campobrigatorio2.setVisible(false); // Ocultar mensagem se o campo estiver preenchido
            }   
            
            if (txestado.getText().trim().isEmpty()) {
                campobrigatorio3.setVisible(true);
                if (txestado.getText().trim().isEmpty()) { // Coloca o foco se o campo estiver vazio
                txestado.requestFocus();
                }
                
            }else {
            campobrigatorio3.setVisible(false); // Ocultar mensagem se o campo estiver preenchido
            }
            
            } 
            else {
            tabela[i][j] = txnome.getText();
            j++;
            tabela[i][j] = txcidade.getText();
            j++;
            tabela[i][j] = txestado.getText();
            j = 0; i++;
            
            //Quando clicar no botão de cadastro
            JOptionPane.showMessageDialog(this, "Os dados foram cadastrados");
            
            //Limpar o painel de cadastro
            txnome.setText(" ");
            txcidade.setText(" ");
            txestado.setText(" ");
            
            //Apagar o campo de mensagens obrigatórias
            
            campobrigatorio1.setVisible(false);
            campobrigatorio2.setVisible(false);
            campobrigatorio3.setVisible(false);

        }
    }//GEN-LAST:event_btsalvarActionPerformed

    private void txnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnomeActionPerformed
        JLabel nomeLabel = new JLabel("Nome:");
        nomeLabel.setBounds(10, 10, 80, 25);
        add(nomeLabel);
    }//GEN-LAST:event_txnomeActionPerformed

    private void btimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btimprimirActionPerformed

       //Transformar matriz em string  
       
       String planilha = " ";
         for(i=0 ; i < tabela.length; i++){
             for(j=0 ; j < 3; j++){
                 if (tabela[i][j] == null) {
                planilha += " Campo vazio "; // Substitui "null" por "Campo vazio"
               } else {
                 planilha += tabela[i][j];
                 planilha += " - ";
             }
             }
             planilha += "\n-------------------------------------------------------------------------------------\n";
         }
        JOptionPane.showMessageDialog(null,planilha);
        System.out.println(planilha);
        
    }//GEN-LAST:event_btimprimirActionPerformed

    private void btcadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcadastroActionPerformed
       painelEntrada.setVisible(false);
       painelcadastro.setVisible(true);
    }//GEN-LAST:event_btcadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoMatriz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoMatriz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btcadastro;
    private javax.swing.JButton btimprimir;
    private javax.swing.JButton btsair;
    private javax.swing.JButton btsalvar;
    private javax.swing.JLabel campobrigatorio1;
    private javax.swing.JLabel campobrigatorio2;
    private javax.swing.JLabel campobrigatorio3;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel imagem;
    private javax.swing.JLabel imagemcadastro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcidade;
    private javax.swing.JLabel lblentrada;
    private javax.swing.JLabel lblestado;
    private javax.swing.JLabel lblnome;
    private javax.swing.JPanel painelEntrada;
    private javax.swing.JPanel painelcadastro;
    private javax.swing.JTextField txcidade;
    private javax.swing.JTextField txestado;
    private javax.swing.JTextField txnome;
    // End of variables declaration//GEN-END:variables
}
